kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: m0wer
    password:
      from_secret: docker_password
    repo: m0wer/docker-taiga
    tags: latest
